---
- name: Run RADON monitoring stack
  hosts: all
  become: true
  vars:
    repo_folder: /tmp/checkout
    mtail_repo_folder: /tmp/mtail

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Install docker module for python
      pip:
        name: docker

    - name: Install docker compose module for python
      pip:
        name: docker-compose

    - name: Git checkout monitoring stack repository
      git:
        repo: 'https://github.com/radon-h2020/radon-monitoring-tool.git'
        dest: "{{ repo_folder }}"
    #        version: latest

    - name: Tear down services
      docker_compose:
        project_src: "{{ repo_folder }}"
        state: absent

    #    - name: Install consul module for python
    #      pip:
    #        name: python-consul

    # This way prometheus auto discover push gateway endpoints
    # of dynamically spawned aws lambda functions.
    # host: the RADON service discovery endpoint. It is integrated
    # to the RADON monitoring server (Prometheus).
#    - name: register mtail exporter service with the RADON consul agent
#      consul:
#        service_name: mtail_exporter
#        service_port: 3903
#        # should automatically get IP of remote host
#        service_address: '52.59.205.49'
#        host: '3.127.254.144'
