version: '3'
services:
  mtail_exporter:
    container_name: mtail_exporter
    image: mtail:latest
    ports:
      - "3903:3903"
    command:
      "-logtostderr --progs /progs/gauge.mtail --logs /logs/foo.log --poll_interval 250ms"
    volumes:
      - /tmp:/logs

      - ./gauge.mtail:/progs/gauge.mtail
