tosca_definitions_version: tosca_simple_yaml_1_3

node_types:

  monitoring_tool:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create: playbooks/create.yml
          delete: playbooks/destroy.yml


topology_template:
  #  inputs:
  #    marker:
  #      type: string
  #      default: default-marker

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    monitoring:
      type: monitoring_tool
      requirements:
        - host: my-workstation