tosca_definitions_version: tosca_simple_yaml_1_3

node_types:

  monitoring_tool:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create: playbooks/mtail/create.yml
          delete: playbooks/mtail/destroy.yml


topology_template:

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: 172.31.38.115
        public_address: 52.59.205.49

    monitoring:
      type: monitoring_tool
      requirements:
        - host: my-workstation