---
- name: Run RADON monitoring stack
  hosts: remote
  become: true
  #  connection: local
  vars:
    repo_folder: /tmp/checkout

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Install docker module for python
      pip:
        name: docker

    - name: Install docker compose module for python
      pip:
        name: docker-compose

    - name: Git checkout monitoring stack repository
      git:
        repo: 'https://github.com/radon-h2020/radon-monitoring-tool.git'
        dest: "{{ repo_folder }}"
    #        version: latest

    - name: Tear down services
      docker_compose:
        project_src: "{{ repo_folder }}"/docker-compose-scripts
        state: absent

    - name: Start services
      docker_compose:
        project_src: "{{ repo_folder }}"/docker-compose-scripts
        state: present
      register: output

    - debug:
        var: output

    - assert:
        that:
          - "pushgateway.pushgateway.state.running"

    - name: Install consul module for python
      pip:
        name: python-consul

    # This way prometheus auto discover push gateway endpoints
    # of dynamically spawned aws lambda functions.
    # host: the RADON service discovery endpoint. It is integrated
    # to the RADON monitoring server (Prometheus).
    - name: register push gateway service with the RADON consul agent
      consul:
        service_name: push_gateway
        service_port: 9091
        host: 3.127.254.144:8500